# This workflow will build a Java project with Maven when a tag is pushed
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
---
name: Java CI with Maven
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - run: echo ::set-env name=TAG::$(echo "$GITHUB_REF" | awk -F / '{print $3}' | sed 's/^v//g')
      shell: bash
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        servers: '[{"id": "bintray", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.APITOKEN}}"}]'
    - name: Build with Maven
      run: |
        mvn install --file pom.xml;
    - name: Deploy
      run: |
        mvn deploy -DpluginVersion=$TAG